[package]
name = "cw721-simple"
version = "0.1.0"
edition = "2021"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []


[dependencies]
schemars = "0.8.10"
serde = { version = "1.0.140", default-features = false, features = ["derive"] }
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.14.0"
cw-utils = "0.14.0"
cw2 = "0.14.0"
cw721 = "0.13.4"
#cw721-base = { version = "0.13.4", features = ["library"] }
cw721-base = { git = "https://github.com/CosmWasm/cw-nfts" }
thiserror = "1.0.32"

[dev-dependencies]
cosmwasm-schema = "1.0.0"
